# Generated by Django 5.0.2 on 2024-02-25 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cupom',
            options={'verbose_name': 'Cupom', 'verbose_name_plural': 'Cupons'},
        ),
    ]
