# Generated by Django 5.0.2 on 2024-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
