# Generated by Django 5.0.2 on 2024-02-19 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produto_estoque'),
    ]

    operations = [
        migrations.AddField(
            model_name='variacao',
            name='variacao_produto_id',
            field=models.CharField(blank=True, default='False-<built-in function id>', max_length=50, null=True),
        ),
    ]
