# Generated by Django 5.0.2 on 2024-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_variacao_variacao_produto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variacao',
            name='variacao_produto_id',
        ),
    ]
